### ISSUE TITLE
System Invalid Cast Exception C#

### ISSUE THREAD

**Issue by jdelange** [RaYell/selenium-webdriver-extensions#89]
My issue is given here: https://groups.google.com/forum/#!topic/selenium-users/iNS0ZqYoNas

Is my issue similar to this issue? https://github.com/RaYell/selenium-webdriver-extensions/issues/13

Thx, Jan

**Comment by RaYell** [comment]
I don't see how it is related? Are you even using our extensions library, because it seems like you're just using Selenium Core.

**Comment by jdelange** [comment]
Hi RaYell, thanks for picking this up. I have installed the NuGet pakackages for the webdriver http://www.nuget.org/packages/Selenium.WebDriver and support classes http://www.nuget.org/packages/Selenium.Support. I thought it might be related because my problem also generates an invalid cast exception in a javascript execution. But I must admit that is just a wild guess.

**Comment by RaYell** [comment]
You're submitting your issue to a wrong project. This project is providing extension methods for Selenium WebDriver as a package called `Selenium.WebDriver.Extensions`. Your problem is related to code Selenium WebDriver project and you should [contact its creators about it](http://www.seleniumhq.org/).

**Comment by jdelange** [comment]
Ok, thanks and sorry about that. My mistake! Jan
